services:
  payara:
    image: payara/micro:latest
    container_name: payara-micro
    ports:
      - "8080:8080"
    volumes:
      - ./target:/opt/payara/deployments:rw
    command: >
      --deploy /opt/payara/deployments/app.war
      --contextRoot /
      --nocluster
    networks:
      - payara-network
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: formation
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - payara-network

volumes:
  mariadb_data:

networks:
  payara-network:
    driver: bridge
